"""Inspect paraphrases generated by the Parrot paraphraser."""

# PYTHONPATH=. python -m src.temp_inspect_parrot_paraphrases --limit 5 --max-return-phrases 5

import argparse

try:
    from src.run_test_100 import JeopardyQuestion, load_questions, normalize_label, question_text, transform_query_text
    from src.search import normalize_query_terms
except ModuleNotFoundError:
    from run_test_100 import JeopardyQuestion, load_questions, normalize_label, question_text, transform_query_text
    from search import normalize_query_terms


PARROT_MODEL_TAG = "prithivida/parrot_paraphraser_on_T5"
DEFAULT_ADEQUACY_THRESHOLD = 0.99
DEFAULT_FLUENCY_THRESHOLD = 0.90
DEFAULT_MAX_RETURN_PHRASES = 5
DEFAULT_MAX_LENGTH = 32


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Show Parrot paraphrases and normalized query terms.")
    parser.add_argument("--limit", type=int, default=5, help="Number of questions to inspect.")
    parser.add_argument(
        "--query-mode",
        choices=["full", "entity"],
        default="full",
        help="Apply the same query transformation used in run_test_100.",
    )
    parser.add_argument(
        "--include-category",
        action="store_true",
        help="Prefix the category to the clue before paraphrasing.",
    )
    parser.add_argument(
        "--max-return-phrases",
        type=int,
        default=DEFAULT_MAX_RETURN_PHRASES,
        help="Maximum number of Parrot paraphrases to keep per question.",
    )
    parser.add_argument(
        "--max-length",
        type=int,
        default=DEFAULT_MAX_LENGTH,
        help="Maximum generated sequence length passed to Parrot.",
    )
    parser.add_argument(
        "--adequacy-threshold",
        type=float,
        default=DEFAULT_ADEQUACY_THRESHOLD,
        help="Parrot adequacy threshold.",
    )
    parser.add_argument(
        "--fluency-threshold",
        type=float,
        default=DEFAULT_FLUENCY_THRESHOLD,
        help="Parrot fluency threshold.",
    )
    parser.add_argument(
        "--do-diverse",
        action="store_true",
        help="Enable Parrot's diverse generation mode.",
    )
    parser.add_argument(
        "--use-gpu",
        action="store_true",
        help="Let Parrot try GPU inference.",
    )
    return parser.parse_args()


def load_parrot():
    try:
        from parrot import Parrot
    except ModuleNotFoundError as error:
        raise RuntimeError(
            "Parrot is not installed. Install it with: "
            "python -m pip install git+https://github.com/PrithivirajDamodaran/Parrot_Paraphraser.git"
        ) from error

    print("Loading Parrot paraphrase model...")
    return Parrot(model_tag=PARROT_MODEL_TAG, use_gpu=False)


def paraphrase_text(
    parrot,
    text: str,
    max_return_phrases: int,
    max_length: int,
    adequacy_threshold: float,
    fluency_threshold: float,
    do_diverse: bool,
    use_gpu: bool,
) -> list[str]:
    paraphrases = parrot.augment(
        input_phrase=text,
        use_gpu=use_gpu,
        max_return_phrases=max_return_phrases,
        max_length=max_length,
        adequacy_threshold=adequacy_threshold,
        fluency_threshold=fluency_threshold,
        do_diverse=do_diverse,
    )

    if not paraphrases:
        return []

    clean_paraphrases = []
    seen = {normalize_label(text)}

    for paraphrase in paraphrases:
        if isinstance(paraphrase, (tuple, list)):
            candidate = str(paraphrase[0]).strip()
        else:
            candidate = str(paraphrase).strip()

        normalized_candidate = normalize_label(candidate)
        if not candidate or normalized_candidate in seen:
            continue

        seen.add(normalized_candidate)
        clean_paraphrases.append(candidate)

    return clean_paraphrases


def print_variant(variant_number: int, label: str, raw_text: str, query_mode: str) -> None:
    transformed_text = transform_query_text(raw_text, query_mode).strip()
    normalized_terms = normalize_query_terms(transformed_text)
    print(f"  Variant {variant_number} ({label})")
    print(f"    raw: {raw_text}")
    print(f"    transformed: {transformed_text}")
    print(f"    normalized: {' '.join(normalized_terms)}")


def inspect_question(
    parrot,
    question_number: int,
    total_questions: int,
    question: JeopardyQuestion,
    query_mode: str,
    include_category: bool,
    max_return_phrases: int,
    max_length: int,
    adequacy_threshold: float,
    fluency_threshold: float,
    do_diverse: bool,
    use_gpu: bool,
) -> None:
    base_query = question_text(question, include_category)
    paraphrases = paraphrase_text(
        parrot,
        text=base_query,
        max_return_phrases=max_return_phrases,
        max_length=max_length,
        adequacy_threshold=adequacy_threshold,
        fluency_threshold=fluency_threshold,
        do_diverse=do_diverse,
        use_gpu=use_gpu,
    )

    print(f"Question {question_number}/{total_questions}")
    print(f"Category: {question.category}")
    print(f"Clue: {question.clue}")
    print(f"Answer: {question.answer}")
    print_variant(0, "original", base_query, query_mode)

    for variant_number, paraphrase in enumerate(paraphrases, start=1):
        print_variant(variant_number, f"parrot {variant_number}", paraphrase, query_mode)

    print()


def main() -> None:
    args = parse_args()
    questions = load_questions()[: args.limit]
    parrot = load_parrot()

    print(f"Inspecting {len(questions)} questions with Parrot")
    print(f"Query mode: {args.query_mode}")
    print(f"Include category: {args.include_category}")
    print(f"Max return phrases: {args.max_return_phrases}")
    print(f"Max length: {args.max_length}")
    print(f"Adequacy threshold: {args.adequacy_threshold}")
    print(f"Fluency threshold: {args.fluency_threshold}")
    print(f"Diverse mode: {args.do_diverse}")
    print(f"Use GPU: {args.use_gpu}")
    print()

    for question_number, question in enumerate(questions, start=1):
        print(f"[parrot] Question {question_number}/{len(questions)}")
        inspect_question(
            parrot=parrot,
            question_number=question_number,
            total_questions=len(questions),
            question=question,
            query_mode=args.query_mode,
            include_category=args.include_category,
            max_return_phrases=args.max_return_phrases,
            max_length=args.max_length,
            adequacy_threshold=args.adequacy_threshold,
            fluency_threshold=args.fluency_threshold,
            do_diverse=args.do_diverse,
            use_gpu=args.use_gpu,
        )


if __name__ == "__main__":
    main()
